language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install nose
before_script:
  - cp ./tests/example_config ./tests/config
# command to run tests
script: nosetests -v
notifications:
  email:
    - api@shotgunsoftware.com
  slack:
    rooms:
      secure: NgcVxptQji2OL7EKx5owh21tOl4rRg51ydYhLPHpBIpBVzlqPxi1jbMHpcbl8mG+GuhU6y1D6kVQgQfuAfIWx5YOc4FodhOFZgeS+eol5RTmEepl1OT6XmAVgEclSZUYQmK25OkcxnFnOV/31RuDPXWcgCvSBZqTy6lAbOZ5VwQ=
